<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
    <ApplicationIcon>Assets\Images\icon.ico</ApplicationIcon>
    <Authors>Oleg Spakov</Authors>
    <Company>Tampere University</Company>
    <PackageIcon>icon.png</PackageIcon>
    <Copyright>Oleg Spakov @ 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\icon.png" />
    <None Remove="Assets\Sounds\activation.mp3" />
    <None Remove="Assets\Sounds\error.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Egorozh.ColorPicker.WPF.Dialog" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="ScottPlot.WPF" Version="4.1.74" />
    <PackageReference Include="System.Management" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Sounds\error.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Sounds\selection.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\icon.png" />
  </ItemGroup>

  <PropertyGroup Condition="'$(VisualStudioVersion)' &gt;= '18.0'">
    <DefineConstants>VS_VERSION_18_0_OR_GREATER</DefineConstants>
  </PropertyGroup>
</Project>
